export const apiMethods = {
  GET: 'GET',
  POST: 'POST',
  PUT: 'PUT',
  DELETE: 'DELETE',
};

export const httpStatusCode = {
  SUCCESS: 200,
  CREATED: 201,
  BAD_REQUEST: 400,
  FORBIDDEN: 401,
  INTERNAL_ERRORS: 500,
  SESSION_TIMEOUT: 408,
};

export const components = {
  LOGIN: 'LOGIN',
  SIGNUP: 'SIGNUP',
  USER_SIGN: 'USER_SIGN',
  SUCCESS: 'SUCCESS',
  HOME: 'HOME',
  FORGET: 'FORGET',
  GET_SSO_USER_DETAILS: 'GET_SSO_USER_DETAILS',
  OTP_VERIFY: 'OTP_VERIFY',
  RESET: 'RESET',
  DASHBOARD: 'DASHBOARD',
  ANNOUNCEMENT: 'ANNOUNCEMENT',
  NETWORK_HEALTH: 'NETWORK_HEALTH',
  HEALTH_CHARTS: 'HEALTH_CHARTS',
  TICKETS: 'TICKETS',
  ADD_TICKET: 'ADD_TICKET',
  EDIT_TICKET: 'EDIT_TICKET',
  VIEW_TICKET: 'VIEW_TICKET',
  CHATS: 'CHATS',
  EDIT_USER: 'EDIT_USER',
  TWO_FACTOR: 'TWO_FACTOR',
  NOTIFICATION: 'NOTIFICATION',
  PROFILE: 'PROFILE',
  PRIVACY_POLICY: 'PRIVACY_POLICY',
  TERMS_CONDITIONS: 'TERMS_CONDITIONS',
  CHARTDATA: 'CHARTDATA'
};

export const gaEvents = {
  LOGIN_VIA_EMAIL: 'login_via_email',
  LOGIN_VIA_GOOGLE: 'login_via_google',
  LOGIN_VIA_MICROSOFT: 'login_via_microsoft',
  NAVIGATE_FORGOT_PASSWORD: 'navigate_forgot_password',
  NAVIGATE_SIGNUP: 'navigate_signup',
  UPDATE_MOBILE_NUMBER: 'update_mobile_number',
  VERIFY_EMAIL_OTP: 'verify_email_otp',
  RESEND_OTP_EMAIL: 'resend_otp_email',
  NAVIGATE_USERS_LIST: 'navigate_users_list',
  NAVIGATE_ANNOUNCEMENTS: 'navigate_announcements',
  NAVIGATE_TICKETS_LIST: 'navigate_tickets_list',
  NAVIGATE_DASHBOARD: 'navigate_dashboard',
  NAVIGATE_CHAT: 'navigate_chat',
  NAVIGATE_FRESHCHAT: 'navigate_freshchat',
  OPEN_NOTIFICATION_SLIDER: 'open_notification_slider',
  NAVIGATE_NOTIFICATIONS: 'navigate_notifications',
  NAVIGATE_PROFILE: 'navigate_profile',
  USER_LOGOUT: 'user_logout',
  CREATE_ACCOUNT_SIGNUP: 'create_account_signup',
  NAVIGATE_LOGIN: 'navigate_login',
  SEND_OTP: 'send_otp_mobile',
  RESEND_OTP: 'resend_otp_mobile',
  SEND_RESET_PASSWORD_LINK: 'send_reset_password_link',
  RESET_PASSWORD: 'reset_password',
  UPDATE_SSO_USER_DETAILS: 'update_sso_user_details',
  APPROVE_USER: 'approve_user',
  OPEN_CREATE_USER: 'open_create_user',
  CREATE_USER: 'create_user',
  NAVIGATE_EDIT_USER: 'navigate_edit_user',
  OPEN_DELETE_USER: 'open_delete_user',
  DELETE_USER: 'delete_user',
  CANCEL_DELETE_USER: 'cancel_delete_user',
  UPDATE_USER_DETAILS: 'update_user_details',
  SEND_ANNOUNCEMENT: 'send_announcement',
  ENABLE_EDIT_USER: 'enable_edit_user',
  NAVIGATE_USERS_OR_TICKETS: 'navigate_users_tickets',
  UPDATE_PROFILE_DETAILS: 'update_profile_details',
  NAVIGATE_VIEW_TICKET: 'navigate_view_ticket',
  NAVIGATE_ADD_TICKET: 'navigate_add_ticket',
  NAVIGATE_EDIT_TICKET: 'navigate_edit_ticket',
  CREATE_NEW_TICKET: 'create_new_ticket',
  UPDATE_TICKET_DETAILS: 'update_ticket_details',
  CONTACT_SALES: 'contact_sales',
  OPEN_PLAY_STORE: 'navigate_play_store',
  OPEN_APP_STORE: 'navigate_app_store',
  PRIVACY_POLICY: 'navigate_privacy_policy',
  TERMS_CONDITIONS: 'navigate_terms_and_conditions',
  CHARTDATA: 'navigate_chartdata'
};

export const aboutSignet =
  'Founded in 1974, SIGNET Electronic Systems Inc. (SIGNET) has grown from a one-person installation services contractor to a 160-person complete technology solutions provider. From design, engineering and installation of a fully independent critical technology system to remote monitoring services, SIGNET delivers comprehensive technology expertise in the areas of communications, security, healthcare communications, wireless connectivity, and mission critical technologies program management.';

export const privacyPolicy = `Any failure by SIGNET to deliver or install products or to otherwise perform caused by reason of any of the following events shall not constitute an event of default or breach of any Terms and Conditions of this Agreement or any other contractual document between the  parties:  strikes,  picket  lines,  boycott  efforts,  fires,  floods,  freeze,  accidents,  war  (whether  or  not  declared),  revolution,  riots, insurrections, acts of God, acts of government (including without limitation any agency or department of the United States of America or any other country, any state or local government), acts of the public enemy, scarcity or rationing of gasoline or other fuel or vital products, inability to obtain materials or labor, and/or any other causes which are not reasonably foreseeable at the time of execution of this Agreement, or which are reasonably beyond the control of SIGNET.\n "To the extent allowed by applicable law, Client will indemnify, defend, and hold harmless SIGNET from and against all direct, indirect and/or any third-party claims, liabilities, damages, and costs (including attorney's fees and all settlement costs) arising out of or relating to this Agreement and/or to Client's or Client's agents, contractors and/or employees' acts or omissions, including any unsafe worksite, building or property condition, regardless of whether or not the claims, liabilities, damages or costs were caused in part by a party indemnified hereunder. The parties agree that there are no third-party beneficiaries express or implied to this or any other contract between Client and SIGNET. To the extent allowed by applicable law, Client will also indemnify, defend, and hold harmless SIGNET from any government or third-party actions, fines and/or penalties arising from Client's failure to follow or abide by any applicable laws, including  without  limitation,  public  bidding  laws  and  prevailing  wage  laws  or  other  employment  laws.  Client's  indemnification  and defense  obligations  shall  all  survive  the  expiration  or  termination  of  this  Agreement,  irrespective  of  the  cause,  and  shall  extend  to claims arising after all services have been fully performed.  This indemnification obligation shall not be limited by any limitation on the amount or type of damages, compensation, or benefits payable by or for Subcontractor under worker's compensation acts, disability benefit acts or other employee benefit acts."`;
